In [2]:
#2.Matrix multiplication
2.1
import numpy as np
import random
M1=np.array([random.randint(0, 50)for _ in range(50)]).reshape(5,10)
M2=np.array([random.randint(0, 50)for _ in range(50)]).reshape(10,5)
print(M1)  
print(M2)
#2.2 M1 * M2.
def Matrix_multip(M1,M2):
    list1 = []
    res = []
    for i in range(0, len(M1[:,0])):
        A = M1[i,:]
        for j in range(0, len(M2[0,:])):
            B = M2[:,j]
            B = B.reshape(1,-1)
            C = A*B
            D = sum(C[0])
            list1.append(D)
        a = np.asarray(list1).reshape(1,-1)
        res.append(a[0])
        list1 = []
    res = np.asarray(res)
    print(res)
    return
if __name__ == "__main__":
    res=Matrix_multip(M1, M2)

[[14 45 27 27 14  1 36 47 49 18]
 [25  5  8  6  8 40  4 50 37  7]
 [35 44 10 19 40 31  1 31 18 31]
 [22 21 35 10 39  9 27 24  6 15]
 [ 4 19  3 15 22  1 23 20 45 32]]
[[40  2 19 16 46]
 [33 29 20 42 47]
 [40  8 48 10 44]
 [48 36 13 43  6]
 [12 14 16 13 32]
 [13 33 44  8 15]
 [10 25 15 12 46]
 [28  2 29  8 42]
 [15 14 50 28 27]
 [50 37  2 29 45]]
[[ 7913  5096  7470  6437 10335]
 [ 4734  2884  6299  3059  6227]
 [ 7745  5179  6152  5756  9206]
 [ 5820  3498  5099  3712  8069]
 [ 4969  3893  4430  4455  6571]]
